// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RPC/ApsakWalletd/apsakwalletd.proto
// </auto-generated>
// Original file comments:
// https://raw.githubusercontent.com/apsaknet/apsakd/master/cmd/apsakwallet/daemon/pb/apsakwalletd.proto
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

namespace Miningcore.Blockchain.Apsak.ApsakWalletd {

  using grpc = global::Grpc.Core;

  public partial class ApsakWalletdRPC
  {
    public ApsakWalletdRPC(string __ServiceName)
    {
      this.__Method_GetBalance = new grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetBalance",
        __Marshaller_ApsakWalletdRPC_GetBalanceRequest,
        __Marshaller_ApsakWalletdRPC_GetBalanceResponse);

      this.__Method_GetExternalSpendableUTXOs = new grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetExternalSpendableUTXOs",
        __Marshaller_ApsakWalletdRPC_GetExternalSpendableUTXOsRequest,
        __Marshaller_ApsakWalletdRPC_GetExternalSpendableUTXOsResponse);

      this.__Method_CreateUnsignedTransactions = new grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateUnsignedTransactions",
        __Marshaller_ApsakWalletdRPC_CreateUnsignedTransactionsRequest,
        __Marshaller_ApsakWalletdRPC_CreateUnsignedTransactionsResponse);

      this.__Method_ShowAddresses = new grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ShowAddresses",
        __Marshaller_ApsakWalletdRPC_ShowAddressesRequest,
        __Marshaller_ApsakWalletdRPC_ShowAddressesResponse);

      this.__Method_NewAddress = new grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "NewAddress",
        __Marshaller_ApsakWalletdRPC_NewAddressRequest,
        __Marshaller_ApsakWalletdRPC_NewAddressResponse);

      this.__Method_Shutdown = new grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Shutdown",
        __Marshaller_ApsakWalletdRPC_ShutdownRequest,
        __Marshaller_ApsakWalletdRPC_ShutdownResponse);

      this.__Method_Broadcast = new grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Broadcast",
        __Marshaller_ApsakWalletdRPC_BroadcastRequest,
        __Marshaller_ApsakWalletdRPC_BroadcastResponse);

      this.__Method_Send = new grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Send",
        __Marshaller_ApsakWalletdRPC_SendRequest,
        __Marshaller_ApsakWalletdRPC_SendResponse);

      this.__Method_Sign = new grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Sign",
        __Marshaller_ApsakWalletdRPC_SignRequest,
        __Marshaller_ApsakWalletdRPC_SignResponse);
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceRequest> __Marshaller_ApsakWalletdRPC_GetBalanceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceResponse> __Marshaller_ApsakWalletdRPC_GetBalanceResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsRequest> __Marshaller_ApsakWalletdRPC_GetExternalSpendableUTXOsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsResponse> __Marshaller_ApsakWalletdRPC_GetExternalSpendableUTXOsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsRequest> __Marshaller_ApsakWalletdRPC_CreateUnsignedTransactionsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsResponse> __Marshaller_ApsakWalletdRPC_CreateUnsignedTransactionsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesRequest> __Marshaller_ApsakWalletdRPC_ShowAddressesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesResponse> __Marshaller_ApsakWalletdRPC_ShowAddressesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressRequest> __Marshaller_ApsakWalletdRPC_NewAddressRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressResponse> __Marshaller_ApsakWalletdRPC_NewAddressResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownRequest> __Marshaller_ApsakWalletdRPC_ShutdownRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownResponse> __Marshaller_ApsakWalletdRPC_ShutdownResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastRequest> __Marshaller_ApsakWalletdRPC_BroadcastRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastResponse> __Marshaller_ApsakWalletdRPC_BroadcastResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendRequest> __Marshaller_ApsakWalletdRPC_SendRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendResponse> __Marshaller_ApsakWalletdRPC_SendResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignRequest> __Marshaller_ApsakWalletdRPC_SignRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignResponse> __Marshaller_ApsakWalletdRPC_SignResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceResponse> __Method_GetBalance { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsResponse> __Method_GetExternalSpendableUTXOs { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsResponse> __Method_CreateUnsignedTransactions { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesResponse> __Method_ShowAddresses { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressResponse> __Method_NewAddress { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownResponse> __Method_Shutdown { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastResponse> __Method_Broadcast { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendResponse> __Method_Send { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignRequest, global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignResponse> __Method_Sign { get; private set; }

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Miningcore.Blockchain.Apsak.ApsakWalletd.ApsakwalletdReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for ApsakWalletdRPC</summary>
    public partial class ApsakWalletdRPCClient : grpc::ClientBase<ApsakWalletdRPCClient>
    {
      public ApsakWalletdRPC __ApsakWalletdRPC { get; private set; }

      /// <summary>Creates a new client for ApsakWalletdRPC</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ApsakWalletdRPCClient(ApsakWalletdRPC __ApsakWalletdRPC, grpc::ChannelBase channel) : base(channel)
      {
        this.__ApsakWalletdRPC = __ApsakWalletdRPC;
      }
      /// <summary>Creates a new client for ApsakWalletdRPC that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ApsakWalletdRPCClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ApsakWalletdRPCClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ApsakWalletdRPCClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceResponse GetBalance(global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetBalance(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceResponse GetBalance(global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__ApsakWalletdRPC.__Method_GetBalance, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceResponse> GetBalanceAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetBalanceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceResponse> GetBalanceAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetBalanceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__ApsakWalletdRPC.__Method_GetBalance, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsResponse GetExternalSpendableUTXOs(global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetExternalSpendableUTXOs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsResponse GetExternalSpendableUTXOs(global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__ApsakWalletdRPC.__Method_GetExternalSpendableUTXOs, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsResponse> GetExternalSpendableUTXOsAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetExternalSpendableUTXOsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsResponse> GetExternalSpendableUTXOsAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.GetExternalSpendableUTXOsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__ApsakWalletdRPC.__Method_GetExternalSpendableUTXOs, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsResponse CreateUnsignedTransactions(global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateUnsignedTransactions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsResponse CreateUnsignedTransactions(global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__ApsakWalletdRPC.__Method_CreateUnsignedTransactions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsResponse> CreateUnsignedTransactionsAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateUnsignedTransactionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsResponse> CreateUnsignedTransactionsAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.CreateUnsignedTransactionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__ApsakWalletdRPC.__Method_CreateUnsignedTransactions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesResponse ShowAddresses(global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ShowAddresses(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesResponse ShowAddresses(global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__ApsakWalletdRPC.__Method_ShowAddresses, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesResponse> ShowAddressesAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ShowAddressesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesResponse> ShowAddressesAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShowAddressesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__ApsakWalletdRPC.__Method_ShowAddresses, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressResponse NewAddress(global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return NewAddress(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressResponse NewAddress(global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__ApsakWalletdRPC.__Method_NewAddress, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressResponse> NewAddressAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return NewAddressAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressResponse> NewAddressAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.NewAddressRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__ApsakWalletdRPC.__Method_NewAddress, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownResponse Shutdown(global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Shutdown(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownResponse Shutdown(global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__ApsakWalletdRPC.__Method_Shutdown, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownResponse> ShutdownAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ShutdownAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownResponse> ShutdownAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.ShutdownRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__ApsakWalletdRPC.__Method_Shutdown, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastResponse Broadcast(global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Broadcast(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastResponse Broadcast(global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__ApsakWalletdRPC.__Method_Broadcast, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastResponse> BroadcastAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BroadcastAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastResponse> BroadcastAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.BroadcastRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__ApsakWalletdRPC.__Method_Broadcast, null, options, request);
      }
      /// <summary>
      /// Since SendRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendResponse Send(global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Send(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Since SendRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendResponse Send(global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__ApsakWalletdRPC.__Method_Send, null, options, request);
      }
      /// <summary>
      /// Since SendRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendResponse> SendAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Since SendRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendResponse> SendAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.SendRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__ApsakWalletdRPC.__Method_Send, null, options, request);
      }
      /// <summary>
      /// Since SignRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignResponse Sign(global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Sign(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Since SignRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignResponse Sign(global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__ApsakWalletdRPC.__Method_Sign, null, options, request);
      }
      /// <summary>
      /// Since SignRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignResponse> SignAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SignAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Since SignRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignResponse> SignAsync(global::Miningcore.Blockchain.Apsak.ApsakWalletd.SignRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__ApsakWalletdRPC.__Method_Sign, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ApsakWalletdRPCClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ApsakWalletdRPCClient(configuration);
      }
    }

  }
}
#endregion
